package com.fenlibao.p2p.model.xinwang.enums;


/**
 * 接口名称
 *
 * @date 2017/5/5 10:40
 */
public enum XinwangInterfaceName {
    PERSONAL_REGISTER_EXPAND("PERSONAL_REGISTER_EXPAND", "个人绑卡注册"),
    QUERY_USER_INFORMATION("QUERY_USER_INFORMATION", "查询用户的所有信息"),
    DIRECT_RECHARGE("DIRECT_RECHARGE","自动充值"),
    RECHARGE("RECHARGE", "充值"),
    WITHDRAW("WITHDRAW", "提现"),
    USER_PRE_TRANSACTION("USER_PRE_TRANSACTION", "用户预处理"),
    RESET_PASSWORD("RESET_PASSWORD","修改密码"),
    MODIFY_MOBILE_EXPAND("MODIFY_MOBILE_EXPAND","预留手机号更新"),
    UNBIND_BANKCARD("UNBIND_BANKCARD","解绑银行卡"),
    DOWNLOAD_CHECKFILE("DOWNLOAD_CHECKFILE","对账文件下载"),
    ESTABLISH_PROJECT("ESTABLISH_PROJECT","创建标的"),
    QUERY_PROJECT_INFORMATION("QUERY_PROJECT_INFORMATION","标的信息查询"),
    UNFREEZE_TRADE_PASSWORD("UNFREEZE_TRADE_PASSWORD","交易密码解冻"),
    USER_AUTO_PRE_TRANSACTION("USER_AUTO_PRE_TRANSACTION", "授权预处理"),
    SYNC_TRANSACTION("SYNC_TRANSACTION", "单笔交易"),
    ASYNC_TRANSACTION("ASYNC_TRANSACTION","批量交易"),
    FREEZE("FREEZE", "资金冻结"),
    QUERY_TRANSACTION("QUERY_TRANSACTION","单笔交易查询"),
    UNFREEZE("UNFREEZE", "资金解冻"),
    DEBENTURE_SALE("DEBENTURE_SALE", "单笔债权出让"),
    CANCEL_DEBENTURE_SALE("CANCEL_DEBENTURE_SALE", "取消债权出让"),
    PERSONAL_BIND_BANKCARD_EXPAND("PERSONAL_BIND_BANKCARD_EXPAND", "个人绑卡"),
    MODIFY_PROJECT("MODIFY_PROJECT", "变更标的"),
    ENTERPRISE_INFORMATION_UPDATE("ENTERPRISE_INFORMATION_UPDATE", "企业信息修改"),
    ENTERPRISE_REGISTER("ENTERPRISE_REGISTER", "企业绑卡注册"),
    ENTERPRISE_BIND_BANKCARD("ENTERPRISE_BIND_BANKCARD", "企业绑卡"),
    CANCEL_PRE_TRANSACTION("CANCEL_PRE_TRANSACTION", "取消已冻结的预处理金额"),
    ENTRUST_IMPORT_USER("ENTRUST_IMPORT_USER", "个人委托开户"),
    AUTHORIZATION_ENTRUST_PAY("AUTHORIZATION_ENTRUST_PAY", "委托支付授权"),
    CONFIRM_CHECKFILE("CONFIRM_CHECKFILE", "对账文件确认"),
    QUERY_AUTHORIZATION_ENTRUST_PAY_RECORD("QUERY_AUTHORIZATION_ENTRUST_PAY_RECORD", "委托支付授权记录查询"),
    ACTIVATE_STOCKED_USER("ACTIVATE_STOCKED_USER", "会员激活"),
    CANCEL_USER_AUTHORIZATION("CANCEL_USER_AUTHORIZATION", "取消用户授权"),
    USER_AUTHORIZATION("USER_AUTHORIZATION", "用户授权"),
    ;
    protected final String code;
    protected final String name;

    XinwangInterfaceName(String code, String name) {
        this.code = code;
        this.name = name;
    }

    public java.lang.String getName() {
        return name;
    }

    public String getCode() {
        return code;
    }
}

